### ISSUE TITLE
Peer-to-peer Code Review [2021/07/27]

### ISSUE THREAD

**Issue by fernandorpm** [gabrielyea/leaderboard#2]
# Peer-to-peer Code Review [2021/07/27]

## Leave your comments here about Gabriel's project!

**Comment by ArthurGC** [comment]
Great job!
![gif](https://media4.giphy.com/media/XreQmk7ETCak0/giphy.gif?cid=ecf05e47dfsa1tv5zaiwlwlvi2rv5lyvv540uzgiivudv924&rid=giphy.gif&ct=g)

**Comment by gabrielyea** [comment]
> Great job!
> ![gif](https://camo.githubusercontent.com/e21f8b90f4459992747c48c7b8a697ad77a3719059e7e542c45a8e202ce1df0c/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f587265516d6b37455443616b302f67697068792e6769663f6369643d656366303565343764667361317476357a6169776c776c7669327276356c797676353430757a67696976756476393234267269643d67697068792e6769662663743d67)

![](https://media1.giphy.com/media/ukJ4Gueb2QgUHcvjro/giphy.gif)
